version: 0.2

# 環境変数
environment_variables:
  DeprecatedEnv:
    secrets-manager:
      HOST_NAME: ${arn:aws:secretsmanager:ap-southeast-2:767397878962:secret:dev/hostname-Ayl55i}:dev/hostname
      DSN: ${arn:aws:secretsmanager:ap-southeast-2:767397878962:secret:dev/neon-2Gu5TB}:dev/neon
      AUTH0_DOMAIN: ${arn:aws:secretsmanager:ap-southeast-2:767397878962:secret:auth0/domain-LuFCaf}:auth0/domain
      AUTH0_CLIENT_ID: ${arn:aws:secretsmanager:ap-southeast-2:767397878962:secret:auth0/client_id-dEVhaD}:auth0/client_id
      AUTH0_CLIENT_SECRET: ${arn:aws:secretsmanager:ap-southeast-2:767397878962:secret:auth0/client_secret-KDj5o9}:auth0/client_secret
      ECR_REGISTRY_URL: 767397878962.dkr.ecr.ap-southeast-2.amazonaws.com

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Starting the pre_build phase...
      - pwd
      
      # 環境変数の登録
      - echo "DSN=${DSN}" >> .env
      - echo "HOST_NAME=${HOST_NAME}" >> .env
      - echo "AUTH0_DOMAIN=${AUTH0_DOMAIN}" >> .env
      - echo "AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}" >> .env
      - echo "AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}" >> .env

      # ECRへのログイン
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin ${ECR_REGISTRY_URL}
  build:
    commands:
      # dockerfileのビルド
      - echo Starting the build phase... 
      - echo Build Docker image ...
      - docker build -t datti-api ./
  post_build:
    commands:
    # imageのpush
      - echo Starting the post_build phase...
      - docker tag ${ECR_REGISTRY_URL}/datti-api:latest
      - docker push ${ECR_REGISTRY_URL}/datti-api:latest
artifacts:
  files: '**/*'
  discard-paths: yes