openapi: 3.0.0
info:
  title: Datti API
  version: 0.0.1
  description: "割り勘管理サービスDattiのWebAPI"
servers:
  - url: https://datti-api-prod.fly.dev
    description: 本番環境のAPIエントリーポイント
  - url: https://datti-api-dev.fly.dev
    description: 開発環境のAPIエントリポイント
security:
- bearerAuth: []

paths:
  /bank/:
    post:
      tags:
        - Banks
      summary: 口座情報の登録
      description: 口座情報情報の登録
      responses:
        '201':
          description: 正常処理のレスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankAccount'
        '401':
          description: アクセストークンによる認証のレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: {type: string, example: "unauthrization error"}
        '500':
          description: 内部エラーのレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: {type: string, example: "internal  error message"}
    get:
      tags:
        - Banks
      summary: 口座情報の参照
      description: 口座情報情報の参照
      responses:
        '200':
          description: 正常処理のレスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankAccount'
        '404':
          description: 指定した講座情報が存在しない
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: {type: string, example: "record not found"}
        '500':
          description: 内部エラーのレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: {type: string, example: "internal error message"}
components:
  schemas:
    BankAccount:
      type: object
      properties:
        uid:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        deletedAt:
          type: string
        accountCode:
          type: string
        bankCode:
          type: string
        branchCode:
          type: string
      required:
        - accountCode
        - bankCode
        - branchCode
  securitySchemes:
    BbearerAuth:
      type: http
      scheme: bearer
      description:  Firebase AuthenticationのIDトークン
