name: Build and Deploy to Fly.io

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: デプロイ先環境名(基本的にprod, devのいずれかを使用)
      ref:
        type: string
        required: true
        description: コミットID(SHA)

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Fly CLI
        run: curl -L https://fly.io/install.sh | sh

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Fly.io app name
        id: get-app-name
        run: |
          if [ "${{ inputs.environment }}" == "prod" ]; then
            echo "FLY_APP_NAME=datti-api-prod" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" == "dev" ]; then
            echo "FLY_APP_NAME=datti-api-dev" >> $GITHUB_ENV
          fi
      
      - name: Fly auth Docker
        run: |
          fly auth docker -t ${{ secrets.FLY_API_TOKEN }} 
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: registry.fly.io/${{ env.FLY_APP_NAME }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          file: ./dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }} # 前ステップで設定したタグを参照する
          labels: ${{ steps.meta.outputs.labels }} # 前ステップで設定したラベルを参照する

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy -i registry.fly.io/${{ env.FLY_APP_NAME }} --org ${{ secrets.FLY_ORG }}

