name: Build and Deploy to Fly.io

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: デプロイ先環境名(基本的にprod, devのいずれかを使用)
      ref:
        type: string
        required: true
        description: コミットID(SHA)

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Authenticate with Fly.io Docker Registry
        run: flyctl auth docker -t ${{ secrets.FLY_API_TOKEN }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Determine Fly.io app name
        id: get-app-name
        run: |
          if [ "${{ inputs.environment }}" == "prod" ]; then
            echo "FLY_APP_NAME=datti-api-prod" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" == "dev" ]; then
            echo "FLY_APP_NAME=datti-api-dev" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./dockerfile  # Dockerfile のパスを指定
          push: true
          tags: registry.fly.io/${{ env.FLY_APP_NAME }}:latest  # ビルドしたイメージを指定

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy -i registry.fly.io/${{ env.FLY_APP_NAME }} --org ${{ secrets.FLY_ORG }}

